### ISSUE TITLE
[ALL] BMP代码目录重构

### ISSUE THREAD

**Issue by freemanlingli** [freemanlingli/BPM#10]
增加EXT等外部目录

**Comment by freemanlingli** [comment]
![default](https://cloud.githubusercontent.com/assets/1860507/6387824/7079d39a-bdcc-11e4-954f-e2c0d534df78.jpg)

**Comment by Verten** [comment]
![image](https://cloud.githubusercontent.com/assets/3843953/6388517/b7468260-bdd5-11e4-9e8d-4d97d500fac1.png)
