### ISSUE TITLE
[bpm][upload file]when uploading the size > 400k, can not upload

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#104]
12:28:58.750 [qtp1917628770-17] ERROR [JDBCExceptionReporter.java:234]：Data truncation: Data too long for column 'content' at row 1 
12:28:58.750 [qtp1917628770-17] ERROR [JDBCExceptionReporter.java:234]：Data truncation: Data too long for column 'content' at row 1 
12:28:58.757 [qtp1917628770-17] DEBUG [UploadfileAction.java:242]：org.springframework.dao.DataIntegrityViolationException: could not insert: [com.app.common.uploadfile.model.Uploadfile]; SQL [insert into ea_uploadfile (content, fileDescription, fileName, fileType, foreignId, url) values (?, ?, ?, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not insert: [com.app.common.uploadfile.model.Uploadfile]

**Comment by Verten** [comment]
应该是数据库字段长度的问题

**Comment by Verten** [comment]
把ea_uploadfile表的字段content改为longblob 之后，依旧不能超过1mb的文件。

需要通过设置参数启动mysql

/usr/local/bin/safe_mysqld -O key_buffer=16M -O table_cache=128 -O sort_buffer=4M -O record_buffer=1M -O max_allowed_packet=24M

**Comment by Verten** [comment]
修改 my.conf

添加一行参数 

max_allowed_packet=24M
