### ISSUE TITLE
[BPM][用户管理][真实用户添加] 得到ITTE员工的ldap的账号，员工姓名，插入USER表中

### ISSUE THREAD

**Issue by freemanlingli** [freemanlingli/BPM#15]
\bpm\src\main\java\com\app\bpm\demo\ImpBpm.java
具体怎么插入，请直接修改这个文件，把数据代码写入

**Comment by shawnshi1984** [comment]
目前ITTE SD Operation Japan All Employee 和 ITTE SD Operations Japan All ASP/ARP 下有57人

**Comment by shawnshi1984** [comment]
IDEA
将整个组添加到BPM的ea-user table中。
比如 infra team，outlook中有ITTE Japan Infra Tools这个邮件地址。他的ID是PDLJAPANIN，可以通过这个ID将下面的所有组员提取到BPM tool中。
测试已经写好并上传到SVN中

**Comment by shawnshi1984** [comment]
Infra team. booking team 已经加进去了啊
