### ISSUE TITLE
[ext][ldap用户认证] 用户登录的实现场景：结合ldap服务

### ISSUE THREAD

**Issue by freemanlingli** [freemanlingli/BPM#20]

**Comment by shawnshi1984** [comment]
[完成]Scenario: "admin"账号登录测试 ，不需要经过LADP认证
[完成]Scenario: ["ea_user表"没有账号]-[ldap没有账号]，显示没有错误提 该用户不存在.
[完成]Scenario: [ea_user表已有账号]登录成功.
[完成]Scenario: [ea_user已有账号] 登陆时输入密码错误，提示：密码错误.
[未完成]Scenario: ["ea_user表"没有账号]-[ldap中有账号]，验证成功后，ea_user表中创建用户信息，在显示 登陆后进入申请 组织架构设置界面

**Comment by shawnshi1984** [comment]
申请组织架构设置页面未完成。
其他部分包括测试已经上传到SVN

**Comment by shawnshi1984** [comment]
用户组织结构申请另外做
