### ISSUE TITLE
[BPM][文件上传]目前工单中的附件插入式保存在web目录下，改成插入数据库中存储文件

### ISSUE THREAD

**Issue by freemanlingli** [freemanlingli/BPM#25]
目前附件暴露在web目录下， 一来不安全，二来回带来版本更新的麻烦。
采取降文件插入数据库中。洪彬可以来问我这个例子代码，有现成代码参考
参考 ea-template 的home.ftl文件中  <a href="common_test_upload_db.do" target="_blank" class="btn btn-xs btn-default">文件上传(存储于数据库)</a>

**Comment by Verten** [comment]
Done, 目前bpm中的附件上传形式已经改成保存到数据库
