### ISSUE TITLE
[bpm][process]每个task之间需要自动assign，不需要选择下一个task的负责人

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#34]

**Comment by Verten** [comment]
在目前的流程图中，如果是分配到组的task，那么就不需要选择任务执行人。
比如，
Prepare BoQ,
Check Quotation, 
Sent Quotation Request to Sourcing Team and get the result, 
Assess The Result,  Create and follow TEF item and IR in TEFIR, 
-Send to order office to place order -Register asset in Carry-in/Out system, 
Scan and Register the asset in BPM and equipman, 
-Create low level bookable unit in BAMS -Inform BU setup to LOM
