### ISSUE TITLE
[bpm][investment process]task name and task movement

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#44]
![image](https://cloud.githubusercontent.com/assets/10985484/6613238/0c9bdd6c-c8cd-11e4-89c1-f13ee2160ac7.png)
change to "Identify Business Impact"

![image](https://cloud.githubusercontent.com/assets/10985484/6613245/23b42be4-c8cd-11e4-9421-d3d3f1ae6250.png)
Check Quotation move to AM team

**Comment by Verten** [comment]
Identify Cost Impact已经更名为Identify Business Impact
![image](https://cloud.githubusercontent.com/assets/3843953/6613429/cb4c3c44-c8c7-11e4-82fe-2d9b8c73c656.png)

Check Quotation 已经移动到 AMTeam
![image](https://cloud.githubusercontent.com/assets/3843953/6613440/ebe817fc-c8c7-11e4-96d0-e8b3e8ed2fa9.png)
