### ISSUE TITLE
js页面缓存的解决方案

### ISSUE THREAD

**Issue by shawnshi1984** [freemanlingli/BPM#5]
在open_task.ftl中，process.js文件缓存不及时，在IE浏览器上这个现象比较明显。

<#include "../../../common/freemarker/include_header.ftl">

<script type="text/javascript" src="<@context_module/>process.js"></script>

<#include '../../manager/${rhs["taskPage"]}'>

**Comment by Verten** [comment]
这个问题具体表现出来是什么状况？
