### ISSUE TITLE
[bpm][suspend task]

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#61]
Steps:
1. submit a request
2. suspend the task
3. revise the request, change something
4. submit the task
5. complete the task

Pop out the error
![image](https://cloud.githubusercontent.com/assets/10985484/6934796/5e455ba4-d875-11e4-93b4-edc2409066b1.png)

**Comment by Verten** [comment]
第三步，Revise之前 数据库的这个字段为true
![image](https://cloud.githubusercontent.com/assets/3843953/6934834/cc53eab4-d86d-11e4-9276-325b996ef36a.png)
但是当我revise之后
![image](https://cloud.githubusercontent.com/assets/3843953/6934838/e98f1f40-d86d-11e4-877b-6d469608e493.png)


因为你revise，保存之后并没有保存这个字段。所以就是null了，建议前台页面用一个 hidden存放着。

**Comment by CheneyJob** [comment]
好的 我去follow 这个bug
