### ISSUE TITLE
[bpm][assign to single]

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#62]
1. When selecting the assignee for person, for example demo
   ![image](https://cloud.githubusercontent.com/assets/10985484/6934869/0f0ef69c-d877-11e4-8efa-224d6606137e.png)
2. When i want to change to other
   ![image](https://cloud.githubusercontent.com/assets/10985484/6934878/20a4dcbe-d877-11e4-9117-ac517a54f9cb.png)
3. change other name, it would pop out:
   ![image](https://cloud.githubusercontent.com/assets/10985484/6934880/30b80cc0-d877-11e4-8b1d-0e89632e0ce3.png)

**Comment by Verten** [comment]
Done
