### ISSUE TITLE
[bpm][assign to person] when assigning to person, and then cancel, it can allow to enter everything, and click the submit

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#64]
Steps:
1. select a person
![image](https://cloud.githubusercontent.com/assets/10985484/6934985/8d04b46e-d878-11e4-8bce-87aa243e3a8e.png)
1. click the submit and the name is placed in the frontend
   ![image](https://cloud.githubusercontent.com/assets/10985484/6934992/a7734784-d878-11e4-88de-7e5dfcf83d49.png)
2. remove the name using keyborad "backspace"
   ![image](https://cloud.githubusercontent.com/assets/10985484/6935005/bb3509c4-d878-11e4-9519-73b20930c858.png)
3. can enter everything in this column
   ![image](https://cloud.githubusercontent.com/assets/10985484/6935014/d05dbb8e-d878-11e4-8468-5c2dca8b453e.png)
4. can allow to complete

**Comment by Verten** [comment]
Done,change to readonly
