### ISSUE TITLE
[bpm][eridoc verify] add the checking for the ericdoc input(for example, need to http://...

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#67]
![image](https://cloud.githubusercontent.com/assets/10985484/6935252/6f18ebc8-d87d-11e4-8ea8-da50f2ba5bb0.png)

**Comment by Verten** [comment]
![image](https://cloud.githubusercontent.com/assets/3843953/6979787/7366db6e-da1b-11e4-9cbc-0e6a2fa9c973.png)


加入了正则表达式的匹配

![image](https://cloud.githubusercontent.com/assets/3843953/6979792/7f5472e2-da1b-11e4-83cd-75202f7f502c.png)
