### ISSUE TITLE
[bpm][eridoc issue]when re-assign, the link would display none

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#69]
Steps:
1. add the link in the EricDoc link, and save
![image](https://cloud.githubusercontent.com/assets/10985484/6936172/0faf868a-d88a-11e4-922c-e78298bf200a.png)
1. click the "Re-assign" or "Return task"
   ![image](https://cloud.githubusercontent.com/assets/10985484/6936174/26c716c6-d88a-11e4-96a3-ff498c300510.png)
2. The EriDoc is blank at this time
   ![image](https://cloud.githubusercontent.com/assets/10985484/6936203/7cf9b0f8-d88a-11e4-8074-bd3857cca1f3.png)

**Comment by Verten** [comment]
Done
