### ISSUE TITLE
[bpm][流程面板]当用户在Process Panel提交log的时候，log的输入框应该清空

### ISSUE THREAD

**Issue by shawnshi1984** [freemanlingli/BPM#7]
当用户提交log的时候，log的输入框应该清空，否则会误导用户重复提交log

**Comment by shawnshi1984** [comment]
![bug_2015022503](https://cloud.githubusercontent.com/assets/7260187/6365685/d51c182a-bcf6-11e4-8128-a18db34bd290.jpg)

**Comment by Verten** [comment]
当log成功提交后，log输入框的内容将会被清空。
