### ISSUE TITLE
[bpm][sub task]当进入到子流程的第一步，在unowned task list 的request id不见了

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#70]
![image](https://cloud.githubusercontent.com/assets/10985484/6959842/dfbb10e2-d957-11e4-98bf-4113f2a19f6c.png)

**Comment by Verten** [comment]
这个情况如果我没记错的话，对于我们的 子任务，貌似就没有提供一个 Request ID字段输入的页面吧？
只有这三个字段，所以 Request ID 就是空的
![image](https://cloud.githubusercontent.com/assets/3843953/6960132/4c84e258-d952-11e4-861c-2835d4127c50.png)

**Comment by richardbpm** [comment]
这里的不是显示子task的ID，是显示主task的ID啊，之前是这样理解的吧，当我cliam完之后，那个request ID就出现在上面啦

**Comment by richardbpm** [comment]
![image](https://cloud.githubusercontent.com/assets/10985484/6960248/8cb6a33a-d95b-11e4-9de3-a9ac944f387f.png)

After Cliam:
![image](https://cloud.githubusercontent.com/assets/10985484/6960255/a6665212-d95b-11e4-8d46-91bafb30a117.png)

**Comment by Verten** [comment]
了解，正在改动

**Comment by Verten** [comment]
Done
