### ISSUE TITLE
[bpm][re-assign]when re-assign, some information can not be saving

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#71]
Steps:
1. add the link and save the link, and then click the re-assign button
![image](https://cloud.githubusercontent.com/assets/10985484/6960000/6b9afcf2-d959-11e4-88f3-9363c10387fb.png)
1. the link can not be saving
   ![image](https://cloud.githubusercontent.com/assets/10985484/6960017/9ba83180-d959-11e4-8c9b-ba98e729403f.png)

**Comment by Verten** [comment]
这个问题我也发现了。因为晨哥写的这个 宏，他的实现逻辑仅仅是暂时存放在页面上的，一定要你点击了 complete之后，才会真正的保存。所以你直接 Re-assign之后，这些值肯定是没有的啦。需要探讨下怎么改动。


目前已经修改了  ericdoc的宏，当你点击save之后，就会去update数据库存放

**Comment by CheneyJob** [comment]
该问题已经修复 ajax 自动update
