### ISSUE TITLE
[bpm][upload file]when uploading the file, will display 下面

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#72]
1. click the "add file"
   ![image](https://cloud.githubusercontent.com/assets/10985484/6961297/a1b718e2-d964-11e4-8501-53c13a85cea8.png)
2. instead of displaying
   ![image](https://cloud.githubusercontent.com/assets/10985484/6961313/d0a309f4-d964-11e4-8249-fbdbabb57510.png)

**Comment by Verten** [comment]
Done
