### ISSUE TITLE
[bpm][export the excel] The pop up window is not friendly

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#74]
![image](https://cloud.githubusercontent.com/assets/10985484/6977576/9a76e566-d9fb-11e4-878a-126058e09f8e.png)

Could change to:
1. ...
2... 
3....
4....

**Comment by richardbpm** [comment]
After no action, the whole page is blank

![image](https://cloud.githubusercontent.com/assets/10985484/6977625/7987eb74-d9fc-11e4-85f0-84b1289af443.png)

**Comment by Verten** [comment]
It has changed to as below:
![image](https://cloud.githubusercontent.com/assets/3843953/6978940/481f7e96-da0e-11e4-9cd5-a109b67899b6.png)
