### ISSUE TITLE
[bpm][add the RTT num]add the RTT num column in the task list

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#75]
![image](https://cloud.githubusercontent.com/assets/10985484/6978616/3f46063e-da11-11e4-83b6-bad61c66dc15.png)

**Comment by Verten** [comment]
![image](https://cloud.githubusercontent.com/assets/3843953/6979843/01be2386-da1c-11e4-994a-fd88c6694569.png)
