### ISSUE TITLE
[bpm][the word need to change]In the Assess the result activity, the operation word would some strange

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#77]
![image](https://cloud.githubusercontent.com/assets/10985484/6979534/4118dc02-da20-11e4-807a-ea387fffee8f.png)

**Comment by richardbpm** [comment]
![image](https://cloud.githubusercontent.com/assets/10985484/6979743/2087b29e-da23-11e4-8368-235b126d4211.png)

**Comment by Verten** [comment]
Done，Change to 
1. "Accept" and "Not Accept"
2. "Need" and "No Need"
