### ISSUE TITLE
[bpm][re-assign button can not work]when re-assign, when submitting, can not work

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#96]
![image](https://cloud.githubusercontent.com/assets/10985484/7062966/6711f9ea-dedd-11e4-9421-dfae9d32ea26.png)

**Comment by richardbpm** [comment]
![image](https://cloud.githubusercontent.com/assets/10985484/7062974/78bc37a0-dedd-11e4-8380-82ac82b2b945.png)

**Comment by CheneyJob** [comment]
This caused by JS error which sometime cannot display on the consle.And has been resolved
