### ISSUE TITLE
[bpm][send email result]after sending the email, need to have the result for successful and fail

### ISSUE THREAD

**Issue by richardbpm** [freemanlingli/BPM#97]

**Comment by Verten** [comment]
@freemanlingli  这里的发送邮件，我们是启动了一个额外的线程来发送的。这样的情况，我们怎么获取发送成功与否？

**Comment by Verten** [comment]
现在已经更改为下图的结果反馈

![image](https://cloud.githubusercontent.com/assets/3843953/7153237/483525ae-e37b-11e4-97b0-6b8293e35f7d.png)
