### ISSUE TITLE
[admin][organize][position define]edit position discription

### ISSUE THREAD

**Issue by shawnshi1984** [freemanlingli/BPM#99]
![asdasdasdas432untitled](https://cloud.githubusercontent.com/assets/7260187/7083037/24f85376-df8f-11e4-986e-6c19a6ff82f7.jpg)

**Comment by shawnshi1984** [comment]
在BaseAction.java, edit_bean_property()
content = BeanUtils.getValue(object, propertyname).toString();没有排空，也就是null。
应该加个try catch

**Comment by shawnshi1984** [comment]
当上一个bug应try catch方法解决以后。
可以正常显示空
但是保存时出现了问题。
似乎是没有找到editAction.java中的edit_bean_property方法，建议调整页面。

**Comment by Verten** [comment]
该bug出现原因两点，
1. BeanUtils.getValue(object, propertyname) 对应object的该属性为空，没有做判断。
2. edit_bean_property.ftl 页面的form action错误，应该为ea_ea_edit_bean_property.do，而不是ea_edit_bean_property.do

目前已经全部更正
